version: '3.8'

services:
  postgres:
    container_name: test-task-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test_task
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  api:
    image: test-task
    restart: always
    build:
      context: .
      dockerfile: dockerfile
      target: development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
    depends_on:
      - postgres
    command: npm run start:dev

volumes:
  postgres-data:
  redis:
    driver: local
